### ISSUE TITLE
what compilers are supported?

### ISSUE THREAD

**Issue by wojdyr** [gknowles/dimcli#9]
Hello,
it's not clear from the project description what compilers are supported or which C++ standard it conforms to. I mean compilers other than VS 2015.
I just tried GCC 6 and it shows a long list of errors, the first one being:
```
cli.cpp:57:11: error: underlying type mismatch in enum ‘enum Dim::Cli::NameListType’
 enum Cli::NameListType {
           ^~~~~~~~~~~~
In file included from cli.cpp:7:0:
../include/dimcli/cli.h:155:25: error: previous definition here
     enum NameListType : int;
                         ^~~
```

**Comment by gknowles** [comment]
There were a number of incompatibilities but it should now compile with gcc 6.2. Some of the tests are still failing for cosmetic reasons (windows vs. *nix line endings), but I've run out of time tonight.

I setup travis to run gcc builds, so it shouldn't break again.

Also, because it uses the filesystem library, gcc requires the you add the stdc++fs library (-lstdc++fs) to the linker. Hopefully this will go away when they finish c++17 support.

But most important, thanks for your interest and the bug report!

Edit: Actually answer the question...
VS 2015 & 2017 are supported, and as of just now so is gcc 6.2.

**Comment by wojdyr** [comment]
Thanks for looking into it and for your reply!

**Comment by aldanor** [comment]
There's seemingly no `<experimental/filesystem>` in apple's clang so is it implicitly unsupported?

**Comment by gknowles** [comment]
Yes, \<experimental/filesystem> is currently required. I've been waiting for the c++17 standard \<filesystem> to start appearing in implementations, if apple's clang has that, simply replacing experimental/filesystem with filesystem and experimental::filesystem with filesystem ought to work.
